[[snippets]]
name = "fzf preview git commit"
trigger = "--preview=commit"
snippet = """
$(
  PLACEHOLDER=$'\\u007b\\u007d' &&
  SINGLE_QUOTE=$'\\u0027' &&
  DOUBLE_QUOTE=$'\\u0022' &&

  printf "--preview=$SINGLE_QUOTE%s && %s | %s$SINGLE_QUOTE" \\
    "[[ $PLACEHOLDER =~ ([0-9a-f]+) ]]" \\
    "git show --color=always --date=iso --pretty=fuller $DOUBLE_QUOTE\\$match[1]$DOUBLE_QUOTE" \\
    "head -n $DOUBLE_QUOTE\\$LINES$DOUBLE_QUOTE"
)"""
evaluate = true
global = true
context = "^fzf\\s"
