[[snippets]]
name = "git"
trigger = "g"
snippet = "git"

[[snippets]]
name = "git add"
trigger = "a"
snippet = "git add"

[[snippets]]
name = "git add"
trigger = "a"
snippet = "add"
global = true
context = "^git\\s"

[[snippets]]
name = "git branch"
trigger = "b"
snippet = "branch"
global = true
context = "^git\\s"

[[snippets]]
name = "git insert origin/develop"
trigger = "#!d"
snippet = "origin/develop"
global = true

[[snippets]]
name = "git insert origin/main"
trigger = "#!m"
snippet = "origin/main"
global = true

[[snippets]]
name = "git commit"
trigger = "c"
snippet = "commit"
global = true
context = "^git\\s"

[[snippets]]
name = "git diff"
trigger = "d"
snippet = "git diff"

[[snippets]]
name = "git diff"
trigger = "d"
snippet = "diff"
global = true
context = "^git\\s"

[[snippets]]
name = "git fetch"
trigger = "f"
snippet = "fetch --all --prune"
global = true
context = "^git\\s"

[[snippets]]
name = "git log --graph"
trigger = "gg"
snippet = "git log --graph --color --date-order --decorate --pretty=format:'%C(auto)%h %d %s %C(cyan bold)(%cr)%Creset' --all"

[[snippets]]
name = "git log --graph"
trigger = "g"
snippet = "log --graph --color --date-order --decorate --pretty=format:'%C(auto)%h %d %s %C(cyan bold)(%cr)%Creset' --all"
global = true
context = "^git\\s"

[[snippets]]
name = "git merge"
trigger = "m"
snippet = "merge"
global = true
context = "^git\\s"

[[snippets]]
name = "git rebase"
trigger = "r"
snippet = "rebase --committer-date-is-author-date --ignore-date --interactive --autosquash"
global = true
context = "^git\\s"

[[snippets]]
name = "git status"
trigger = "s"
snippet = "git status --short --branch"

[[snippets]]
name = "git status"
trigger = "s"
snippet = "status --short --branch"
global = true
context = "^git\\s"

[[snippets]]
name = "git worktree"
trigger = "w"
snippet = "worktree"
global = true
context = "^git\\s"

[[snippets]]
name = "list git worktree"
trigger = "remove"
snippet = """
remove $(
  git worktree list \\
  | fzf \\
    --height=5 \\
  | cut -d' ' -f1
)"""
evaluate = true
global = true
context = "^git\\sworktree\\s"
